### ISSUE TITLE
Does Month need to be written out? Is the digit ok?

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/metadata-template-transformation#17]
The JGI template captures collection month spelled out. In the JGI template an enumeration of the 12 months spelled out is provided. NMDC [collection_date](https://microbiomedata.github.io/nmdc-schema/collection_date/) collects month as MM digits.

@aclum , @emileyfadrosh : can you inform, how does JGI use this / store this? Do we need to convert the month digit to be spelled out when we export the JGI template?

**Comment by aclum** [comment]
This is stored as is in the project management system, there are web links that pull up the original submission based on a sample id. In other places, for example the data warehouse postgres database the information is converted into a timestamp (schema dw, table samples column collection_time)
example of internal web view of metadata submission
![Screenshot 2023-05-31 at 10 24 12 AM](https://github.com/microbiomedata/metadata-template-transformation/assets/8196591/c4c18795-5cef-400a-9a18-4c0b4c43df76)

For now we should export this in the current JGI format, otherwise the JGI metadata forms won't be consistent.

**Comment by mslarae13** [comment]
thank you! 
https://github.com/microbiomedata/metadata-template-transformation/issues/28
