### ISSUE TITLE
source_mat_id is no longer required

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/metadata-template-transformation#30]
Previously, NMDC was using source_mat_id to collect the globally unique ID for submissions.
This is no longer required as NMDC can mint biosample identifiers. Need to update this requirement for MUTTs

**Comment by mslarae13** [comment]
@sujaypatil96 I think you fixed this, right? Can you link the PR?

**Comment by sujaypatil96** [comment]
I didn't go through the usual make PR and merge it into _main_ branch process for this, but instead pushed up to _main_ directly, so instead of a PR, there is a direct commit associated with this fix: https://github.com/microbiomedata/metadata-template-transformation/commit/ce787039efe951e7d4e45971ebd6ac09b7472db0
